#!/usr/bin/with-contenv bash

source /etc/env

if [[ $APP == "radarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/Radarr.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "sonarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/NzbDrone.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "lidarr" ]]; then
    exec s6-setuidgid hotio mono --debug /app/Lidarr.exe --nobrowser --data=/config $ARGS
fi

if [[ $APP == "jackett" ]]; then
    exec s6-setuidgid hotio mono --debug /app/JackettConsole.exe --NoRestart --ListenPublic $ARGS
fi

if [[ $APP == "nzbhydra2" ]]; then
    exec s6-setuidgid hotio /app/nzbhydra2 --nobrowser --datafolder /config $ARGS
fi

if [[ $APP == "nzbget" ]]; then
    exec s6-setuidgid hotio /app/nzbget --server --option OutputMode=log --configfile /config/nzbget.conf $ARGS
fi

if [[ $APP == "jdownloader" ]]; then
    # idk why this is needed?
    chown -R hotio:hotio /app
    exec s6-setuidgid hotio java -Djava.awt.headless=true -jar /app/JDownloader.jar $ARGS
fi